# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 夜行者之路
email: zougangmu@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  曾经梦想仗剑走天涯，后来因为加班太多放弃
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://me.oadoc360.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  
github_username: php-cpm 
permalink: date

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
tag_page_data:
  sitemap: false
ignored_tags: [tags,to,ignore]

paginate: 30
paginate_path: "blog/:num"